services:
  - type: web
    name: telegram-pdf-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false     # add in Render dashboard
      - key: PUBLIC_URL
        sync: false     # set to your Render web service URL, e.g. https://<service>.onrender.com
